name: Build & Test

on:
  push:
    branches: [master]
  workflow_dispatch:

# permissions:
#   contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build with ncc
        run: |
          npm install
          npm run build

      - name: Invoke echo 1 workflow using this action
        uses: ./
        with:
          workflow: Message Echo 1
          inputs: '{"message": "blah blah"}'

      - name: Invoke echo 2 workflow using this action
        uses: ./
        with:
          workflow: echo-2.yaml

      - name: Invoke echo 1 workflow by id
        uses: ./
        with:
          workflow: "1854247"
          inputs: '{"message": "Mango jam"}'

      # - name: Push dist back to GitHub
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}

      # - name: Invoke external workflow using this action
      #   uses: ./
      #   with:
      #     workflow: Deploy To Kubernetes
      #     repo: benc-uk/dapr-store
      #     token: ${{ secrets.PERSONAL_TOKEN }}
      #     ref: master
